SubReddit v2/objects/SubReddit__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Social Networking</fullName>
                </value>
                <value>
                    <fullName>Viral</fullName>
                </value>
                <value>
                    <fullName>Software Employees</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subreddit__c</fullName>
        <label>Subreddit</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>SubReddit</label>
    <nameField>
        <label>SubReddit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubReddit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v1/classes/subRedditController.cls
public  class subRedditController {

    @AuraEnabled
    public  static list<SubReddit__c> subRedditSearchkey(String searchKey) {
        string searchKeyword = '%' + searchKey + '%';
		
        // create contact list to store search result 
         list<SubReddit__c> subRedditListRecord = new list<SubReddit__c>();
      
        // query contact records
         for(SubReddit__c subRObj : [Select id,Name, Category__c, No_Of_Upvotes__c,No_Of_Downvotes__c
                             From SubReddit__c
                             WHERE Name LIKE : searchKeyword]){
                                subRedditListRecord.add(subRObj);
                                system.System.debug('Name for loop'+subRObj.Name);
         }
         system.System.debug('for loop outside'+subRedditListRecord);

          if(subRedditListRecord.size() == 0){
             throw new AuraHandledException('No Record Found..'); 
          }
          
         return subRedditListRecord;
    }

    @AuraEnabled
    public static list<SubReddit__c> getSubRedditDefault(string noUseParameter){

        list<SubReddit__c> SubRedditListDefault = new list<SubReddit__c>();

        for(SubReddit__c SRObj : [Select id,Name, Category__c,No_Of_Downvotes__c,No_Of_Upvotes__c
        From SubReddit__c ORDER by No_Of_Upvotes__c desc NULLS LAST limit 10]){
            SubRedditListDefault.add(SRObj);
        }
       system.debug('noUseParameter :'+noUseParameter );
         if(SubRedditListDefault.size() == 0){
            throw new AuraHandledException('No Record Found..');
         }
         system.debug('SubRedditListDefault :'+SubRedditListDefault);

        return SubRedditListDefault;
    }
}