SubReddit v2/objects/SubReddit__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Social Networking</fullName>
                </value>
                <value>
                    <fullName>Viral</fullName>
                </value>
                <value>
                    <fullName>Software Employees</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subreddit__c</fullName>
        <label>Subreddit</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>SubReddit</label>
    <nameField>
        <label>SubReddit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubReddit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/objects/Vote__c.object
<CustomObject>
    <fields>
        <fullName>Source_Id__c</fullName>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Votes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vote</label>
        <type>Checkbox</type>
    </fields>
    <label>Vote</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Vote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/classes/voteWrapper.cls
public with sharing class voteWrapper {
        @AuraEnabled
        public static list<SubredditWrapperClass1> subRedditWrapperMethod(Id userId) {
            List<SubredditWrapperClass1> wrapperList = new List<SubredditWrapperClass1>();
            SubredditWrapperClass1 WrapList;
            for(SubReddit__c subObj : [Select id
            , Name
            , Category__c
            , No_Of_Downvotes__c
            , No_Of_Upvotes__c
            , Owner.Name
            , Owner.id
            From SubReddit__c ORDER BY No_Of_Upvotes__c desc]){
                WrapList = new SubredditWrapperClass1();
                WrapList.subredditrec = subObj;
                
                for(Vote__c voteObj :[Select id
                , Vote__c
                , Source_Id__c
                , User__c 
                , CreatedDate
                from vote__c Where Source_Id__c =:subObj.id  AND  User__c =: userId  ORDER BY CreatedDate desc Limit 1]){
                    WrapList.voterec = voteObj;
                    WrapList.voteValue = voteObj.Vote__c;
                    if(voteObj.Vote__c == true){
                        WrapList.upLike = true;
                        WrapList.downLike = false;
                    }else  if(voteObj.Vote__c == false){
                        WrapList.upLike = false;
                        WrapList.downLike = true;
                    }else {
                        WrapList.upLike = true;
                        WrapList.downLike = true;
                    }
            }
             wrapperList.add(WrapList);
    
        }
        if(wrapperList.size() == 0){
            throw new AuraHandledException('No Record Found..');
         }
         for(SubredditWrapperClass1 ls:wrapperList){
            system.debug('wrapperList '+ls);
         }
        return wrapperList;
    }
        public class SubredditWrapperClass1{
            @AuraEnabled
            public SubReddit__c subredditrec;
            @AuraEnabled
            public Vote__c voterec;
            @AuraEnabled
            public Boolean voteValue;
            @AuraEnabled
            public Boolean upLike;
            @AuraEnabled
            public Boolean downLike;
        }





















// @AuraEnabled
// public static list<SubredditWrapperClass1> subRedditWrapperMethod(Id userId) {
//     List<SubredditWrapperClass1> ls = new List<SubredditWrapperClass1>();

// list<SubReddit__c> subRedditList = [Select id
// , Name
// , Category__c
// , No_Of_Downvotes__c
// , No_Of_Upvotes__c
// , Owner.Name
// , Owner.id
// From SubReddit__c ORDER BY No_Of_Upvotes__c desc];
      
       
// list<Vote__c> voteList = [Select id
//         , Vote__c
//         , Source_Id__c
//         , User__c
//         from vote__c Where  User__c =: userId];

// SubredditWrapperClass1 wrapperList = new SubredditWrapperClass1();
// wrapperList.subredditrec=subRedditList;
// wrapperList.voterec=voteList;
// ls.add(wrapperList);
// for(SubredditWrapperClass1 ls1: ls){
//     system.debug('SubredditWrapperClass1 '+ls1);
//     }
//     return ls;
//     }

//     //Wrapper Class
//         public class SubredditWrapperClass1{
//         @AuraEnabled public List<SubReddit__c> subredditrec;
//         @AuraEnabled public List<Vote__c> voterec;


        // public SubredditWrapperClass1(List<SubReddit__c> subredditrec,
        //                              List<Vote__c> voterec
        //                               ){
        //     this.subredditrec = subredditrec;
        //     this.voterec = voterec;
        // }
}