SubReddit v2/objects/SubReddit__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Social Networking</fullName>
                </value>
                <value>
                    <fullName>Viral</fullName>
                </value>
                <value>
                    <fullName>Software Employees</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subreddit__c</fullName>
        <label>Subreddit</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>SubReddit</label>
    <nameField>
        <label>SubReddit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubReddit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/objects/Vote__c.object
<CustomObject>
    <fields>
        <fullName>Source_Id__c</fullName>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Votes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vote</label>
        <type>Checkbox</type>
    </fields>
    <label>Vote</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Vote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/classes/subRedditController.cls
public  class subRedditController {
    @AuraEnabled
    public static list<SubredditWrapperClass1> subRedditSearchkey(Id userId, String searchKey) {

        string searchKeyword = '%' + searchKey + '%';

        List<SubredditWrapperClass1> wrapperList = new List<SubredditWrapperClass1>();
        SubredditWrapperClass1 WrapListForSearch;
        for(SubReddit__c subObj : [Select id
        , Name
        , Category__c
        , No_Of_Downvotes__c
        , No_Of_Upvotes__c
        , Owner.Name
        , Owner.id
        From SubReddit__c WHERE Name LIKE : searchKeyword ORDER BY No_Of_Upvotes__c desc]){
            WrapListForSearch = new SubredditWrapperClass1();
            WrapListForSearch.subredditrec = subObj;
            
            for(Vote__c voteObj :[Select id
            , Vote__c
            , Source_Id__c
            , User__c 
            , CreatedDate
            from vote__c Where Source_Id__c =:subObj.id  AND  User__c =: userId  ORDER BY CreatedDate desc Limit 1]){
                WrapListForSearch.voterec = voteObj;
                WrapListForSearch.voteValue = voteObj.Vote__c;
                if(voteObj.Vote__c == true){
                    WrapListForSearch.upLike = true;
                    WrapListForSearch.downLike = false;
                }else  if(voteObj.Vote__c == false){
                    WrapListForSearch.upLike = false;
                    WrapListForSearch.downLike = true;
                }else {
                    WrapListForSearch.upLike = true;
                    WrapListForSearch.downLike = true;
                }
        }
         wrapperList.add(WrapListForSearch);

    }
    if(wrapperList.size() == 0){
        throw new AuraHandledException('No Record Found..');
     }
     for(SubredditWrapperClass1 ls:wrapperList){
        system.debug('wrapperList '+ls);
     }
    return wrapperList;
}
    public class SubredditWrapperClass1{
        @AuraEnabled
        public SubReddit__c subredditrec;
        @AuraEnabled
        public Vote__c voterec;
        @AuraEnabled
        public Boolean voteValue;
        @AuraEnabled
        public Boolean upLike;
        @AuraEnabled
        public Boolean downLike;
    }
}

















    // @AuraEnabled
    // public  static list<SubReddit__c> subRedditSearchkey(String searchKey) {
    //     string searchKeyword = '%' + searchKey + '%';
		
    //     // create contact list to store search result 
    //      list<SubReddit__c> subRedditListRecord = new list<SubReddit__c>();
      
    //     // query contact records
    //      for(SubReddit__c subRObj : [Select id,Name, Category__c, No_Of_Upvotes__c,No_Of_Downvotes__c
    //                          From SubReddit__c
    //                          WHERE Name LIKE : searchKeyword]){
    //                             subRedditListRecord.add(subRObj);
    //                             system.System.debug('Name for loop'+subRObj.Name);
    //      }
    //      system.System.debug('for loop outside'+subRedditListRecord);

    //       if(subRedditListRecord.size() == 0){
    //          throw new AuraHandledException('No Record Found..'); 
    //       }
          
    //      return subRedditListRecord;
    // }

    // @AuraEnabled
    // public static list<SubReddit__c> getSubRedditDefault(string noUseParameter){

    //     list<SubReddit__c> SubRedditListDefault = new list<SubReddit__c>();

    //     for(SubReddit__c SRObj : [Select id,Name, Category__c,No_Of_Downvotes__c,No_Of_Upvotes__c
    //     From SubReddit__c ORDER by No_Of_Upvotes__c desc NULLS LAST limit 100]){
    //         SubRedditListDefault.add(SRObj);
    //     }
    //    system.debug('noUseParameter :'+noUseParameter );
    //      if(SubRedditListDefault.size() == 0){
    //         throw new AuraHandledException('No Record Found..');
    //      }
    //      system.debug('SubRedditListDefault :'+SubRedditListDefault);

    //     return SubRedditListDefault;
    // }