SubReddit v1/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Comments__c</fullName>
        <label>No Of Comments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubReddit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubReddit</label>
        <referenceTo>SubReddit__c</referenceTo>
        <relationshipLabel>Posts</relationshipLabel>
        <relationshipName>Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/objects/SubReddit__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subreddit__c</fullName>
        <label>Subreddit</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>SubReddit</label>
    <nameField>
        <label>SubReddit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubReddit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/classes/postController.cls
public with sharing class postController {
    @AuraEnabled
    public  static list<Post__c> postSearchkey(String postSearchKey, id redditids) {
        string PostearchKeyword = '%' + postSearchKey + '%';
		
        // create contact list to store search result 
         list<Post__c> postSearchListRecords = new list<Post__c>();
      
        // query contact records
         for(Post__c postObj : [Select id,Name, No_Of_Comments__c,SubReddit__c, Body__c,Title__c, No_Of_Upvotes__c,No_Of_Downvotes__c
                             From Post__c
                             WHERE Name LIKE : PostearchKeyword AND SubReddit__c=:redditids]){
                                postSearchListRecords.add(postObj);
                                system.System.debug('Name for loop'+postObj.Name);
         }
         system.System.debug('for loop outside'+postSearchListRecords);

          if(postSearchListRecords.size() == 0){
             throw new AuraHandledException('No Record Found..'); 
          }   
         return postSearchListRecords;
    }

    @AuraEnabled
    public static list<Post__c> getpostDefault(id redditIdForDefault){

        list<Post__c> postListDefault = new list<Post__c>();

        for(Post__c SRObj : [Select id,Name, No_Of_Comments__c,SubReddit__c, Body__c, Title__c, No_Of_Upvotes__c,No_Of_Downvotes__c
        From Post__c where SubReddit__c=:redditIdForDefault ORDER by No_Of_Upvotes__c desc NULLS LAST limit 10]){
            postListDefault.add(SRObj);
        }
       system.debug('noUseParameter :' );
         if(postListDefault.size() == 0){
            throw new AuraHandledException('No Record Found..');
         }
         system.debug('postListDefault :'+postListDefault);

        return postListDefault;
    }
}