SubReddit v1/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Comments__c</fullName>
        <label>No Of Comments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubReddit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubReddit</label>
        <referenceTo>SubReddit__c</referenceTo>
        <relationshipLabel>Posts</relationshipLabel>
        <relationshipName>Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/objects/SubReddit__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subreddit__c</fullName>
        <label>Subreddit</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>SubReddit</label>
    <nameField>
        <label>SubReddit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubReddit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/objects/Vote__c.object
<CustomObject>
    <fields>
        <fullName>Source_Id__c</fullName>
        <label>Source Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Votes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Vote</label>
        <type>Checkbox</type>
    </fields>
    <label>Vote</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Vote Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Subreddit v3/classes/postController.cls
public with sharing class postController {

    @AuraEnabled
    public  static list<postWrapperClass> postSearchkey(String postSearchKey, id redditids, Id userId) {
        string PostearchKeyword = '%' + postSearchKey + '%';

        String soqlQuery = 'Select id,Name, No_Of_Comments__c,SubReddit__c, Body__c,Title__c, No_Of_Upvotes__c,No_Of_Downvotes__c' +
        ' From Post__c';
 
if(postSearchKey!= ''){
    soqlQuery += ' WHERE Name LIKE : PostearchKeyword AND SubReddit__c=:redditids ORDER BY No_Of_Upvotes__c desc';
}else{
    soqlQuery += ' WHERE SubReddit__c=:redditids ORDER BY No_Of_Upvotes__c desc';
}
//list<Post__c> obj = database.query(soqlQuery);
system.debug('soqlQuery :'+database.query(soqlQuery));
system.debug('soqlQuery :'+soqlQuery);
		
List<postWrapperClass> wrapperList = new List<postWrapperClass>();
postWrapperClass WrapListForSearch;
      
        // query contact records
         for(Post__c postObj : database.query(soqlQuery)){
            WrapListForSearch = new postWrapperClass();
            WrapListForSearch.postRec = postObj;

            for(Vote__c voteObj :[Select id
            , Vote__c
            , Source_Id__c
            , User__c 
            , CreatedDate
            from vote__c Where Source_Id__c =:postObj.id  AND  User__c =: userId  ORDER BY CreatedDate desc Limit 1]){
                WrapListForSearch.voterec = voteObj;
                if(voteObj.Vote__c == true){
                    WrapListForSearch.upLike = true;
                    WrapListForSearch.downLike = false;
                }else  if(voteObj.Vote__c == false){
                    WrapListForSearch.upLike = false;
                    WrapListForSearch.downLike = true;
                }else {
                    WrapListForSearch.upLike = true;
                    WrapListForSearch.downLike = true;
                }
        }
         wrapperList.add(WrapListForSearch);                                
         }  
         return wrapperList;
    }

    public class postWrapperClass{
        @AuraEnabled public Post__c postRec;
        @AuraEnabled public Vote__c voterec;
        @AuraEnabled public Boolean upLike;
        @AuraEnabled public Boolean downLike;
    }









    // @AuraEnabled
    // public static list<Post__c> getpostDefault(id redditIdForDefault){

    //     list<Post__c> postListDefault = new list<Post__c>();

    //     for(Post__c SRObj : [Select id,Name, No_Of_Comments__c,SubReddit__c, Body__c, Title__c, No_Of_Upvotes__c,No_Of_Downvotes__c
    //     From Post__c where SubReddit__c=:redditIdForDefault ORDER by No_Of_Upvotes__c desc NULLS LAST limit 10]){
    //         postListDefault.add(SRObj);
    //     }
    //    system.debug('noUseParameter :' );
    //      if(postListDefault.size() == 0){
    //         throw new AuraHandledException('No Record Found..');
    //      }
    //      system.debug('postListDefault :'+postListDefault);

    //     return postListDefault;
    // }
}